### ISSUE TITLE
SF2_MiV_ADC_Demo

### ISSUE THREAD

**Issue by salmansheikh** [Future-Electronics-Design-Center/Creative-Eval-Board#2]
I have modified the program for the ADC demo but everytime I run the program thru the debugger, it seems to run the unmodified original executable every time and doesn't reflect any additional code or print statements. I tried cleaning the project and re-running. Is there some flash that holds the program on the SF2 FPGA that is not getting updated every time I do a new compile?  Like I modified and added another printf statement (line 78) and it doesn't reflect that in the run. 
<img width="857" alt="no_change_in_code_run" src="https://user-images.githubusercontent.com/3300400/62885434-e9b64200-bd06-11e9-901e-34beeaae1484.PNG">

**Comment by salmansheikh** [comment]
Why would a program that I am running seem not to run but the stock ADC software program keep running no matter how many changes I make to and rebuild and run or debug. It almost seems like its permanently in some memory somewhere on this board.

**Comment by Future-Electronics-Design-Center** [comment]
Hi! 

Yes the MiV code is kept in the eNVM of the FPGA for it to start at power-up. You can override the MiV firmware by replacing it with yours using the "Update eNVM Memory Content" in the Design Flow tab of Libero software. You have to update the MiV_Boot Client in the eNVM Update Tool. Also, the Mi-V core Reset Vector is set to read this eNVM client so you can change it to point to 0x8000 0000 (RAM) instead of the internal Flash memory (0x6000 0000), See design document for the full Memory map. This change will help you debug your firmware in RAM from the SoftConsole debugger.
